Iter5
BillyTilly/yndxpract pull request #5
Opened 2024-02-12 16:19 UTC by BillyTilly

2024-02-14 22:42 UTC, valentinsoe requested changes
Спасибо за работу.
Написал ряд замечаний.
Также добавлю, что не стоит весь код писать в одном файле main. Его пока немного, но все-таки все кроме инициализации приложения лучше оттуда вынести.

Что касается тестов - то они покрывают только "успешный сценарий", это не очень полное покрытие. А еще второй тест зависит от первого, хотя никаких гарантий того, что тесты будут выполняться в том порядке, в котором они идут в файле нам никто не дает. Это нужно исправить.

2024-02-14 22:42 UTC, valentinsoe commented on config/config.go
> +	if string(AppConfig.Host) != "localhost:8080" {
Не понял почему для всех AppConfig.Host отличных от localhost:8080 мы проигнорируем значения baseUrl, что из параметров командной строки, что из переменных окружения.

2024-02-14 22:42 UTC, valentinsoe commented on config/config.go
> +func GenerateConfig() {
Не самое удачное название. Мы конфигурацию все-таки не генерируем, а просто читаем:)

2024-02-14 22:42 UTC, valentinsoe commented on config/config.go
> +	}
В целом чуть более простым подходом будет сначала просто считать параметры командной строки в структуру, а потом переменные окружения "поверх" в эту же структуру.

2024-02-14 22:42 UTC, valentinsoe commented on cmd/shortener/main.go
> +var a = make(map[string]string)
Не самое удачое название переменной:) 
Она имеет большое значение и используется в "далеких" кусках кода.

2024-02-14 22:42 UTC, valentinsoe commented on cmd/shortener/main.go
> +var generatedURL string
Не понимаю смысл данной переменной - мы в нее записываем последний сгенерированный ключ. И при каждом вызове оно будет меняться.
Если код требует "дополнительных" данных для того чтобы работали тесты - что-то пошло не так.

2024-02-14 22:42 UTC, valentinsoe commented on cmd/shortener/main.go
> +	r.GET("/:key", redirectHandler)
Мы добавили в url ключ :key, но почему-то в коде хендлера им не пользуемся совсем.

2024-02-14 22:42 UTC, valentinsoe commented on cmd/shortener/main_test.go
> +			request: "/" + generatedURL,
Данный тест зависит от предыдущего теста. Так делать категорически не стоит.
Почему бы просто не инициализировать переменную a перед тестом, так, как нужно тесту?

2024-02-19 12:17 UTC, BillyTilly commented on cmd/shortener/main_test.go
> +			request: "/" + generatedURL,
Исправил

2024-02-19 12:18 UTC, BillyTilly commented on cmd/shortener/main.go
> +	r.GET("/:key", redirectHandler)
Вот тут вопрос возникает ,  key как ключ у нас будет когда запрос напрямую попадет в приложение  и мы его обработаем r.GET("/:key", redirectHandler) , а как с тестом быть в такой ситуации?

2024-02-19 12:19 UTC, BillyTilly commented on cmd/shortener/main.go
> +var a = make(map[string]string)
Исправил

2024-02-19 12:19 UTC, BillyTilly commented on config/config.go
> +	}
Думал , что так более наглядно покажу , что главнее

2024-02-19 12:48 UTC, BillyTilly commented on config/config.go
> +	if string(AppConfig.Host) != "localhost:8080" {
Иначе здесь всегда отваливаюсь , хоть и пытался сам host как дефолтный подставлять
![Снимок](https://github.com/BillyTilly/yndxpract/assets/72972338/0a483545-d62c-4f15-ab40-6cca7ac13ca3)

2024-02-19 22:36 UTC, valentinsoe requested changes
Спасибо за исправления, стало лучше.

Ответ про непрохождение теста не принимаю - он никак не может быть связан с указанным в комментарии условием.
Как передать параметры в URL в тестах тоже написал, это надо исправить.

Повторюсь про разделение кода на модули. В рамках данного спринта я это не буду требовать, но с добавлением кода следующих спринтов это надо сделать.
Подсказка - сделать это раньше проще чем позже:)

2024-02-19 22:36 UTC, valentinsoe commented on config/config.go
> +	if string(AppConfig.Host) != "localhost:8080" {
Данный тест пытается отправить ссылку на сокращение. BaseURL в этом тесте никак не задействован.
Лучший способ проверить - закомментировать данную строчку и проверить, что данный тест проходит.

2024-02-19 22:36 UTC, valentinsoe commented on config/config.go
> +	}
Да, но так у нас есть отдельно локальные переменные фукнции, в которые мы читаем флаги, отдельно глобальная переменная пакета, в которую мы читаем переменные окружения, а потом патчим.
Не проще ли четыре строки:
flag.StringVar(...)
flag.StringVar(...)
flags.Parse()
env.Parse(&appConfig)

2024-02-19 22:36 UTC, valentinsoe commented on cmd/shortener/main.go
> +	r.GET("/:key", redirectHandler)
Если в хендлере мы ожидаем, что key будет в gin.Context,
То в тесте надо его добавить в gin.Context
```
c, _ := gin.CreateTestContext(w)
c.Params = []gin.Param{gin.Param{Key: "key", Value: "shortened_url_should_be_here"}}

```

2024-02-19 22:36 UTC, valentinsoe commented on cmd/shortener/main.go
> +	if stringedBody == "" {
Стоит это проверять до генерации ключа. Ну и проверять len(body) != 0, до конвертации его к строке.

2024-02-19 22:36 UTC, valentinsoe commented on cmd/shortener/main_test.go
> +	generatedURLs["ViFL5L"] = "http://yandex.ru"
Я бы рекомендовал не добавить ключ, а перезаписать всю map, чтобы прочие тесты, которые в generatedURLs писали, не могли бы никак повлиять на результаты этого теста.
`generatedURLs = map[string]string {"shortUrl": "longUrl"}`

Дополнительно поможет, если не хранить сокращенные ссылки, как глобальную переменную, а добавить структуру "хранилище" и передавать ее в хендлер при создании. Позволит легко подменять ее целиком.

2024-02-20 09:05 UTC, BillyTilly commented on config/config.go
> +	if string(AppConfig.Host) != "localhost:8080" {
Вот теперь еще вообще не понял, до этого не работало без, может я в другие тесты смотрел , поправил

2024-02-20 09:05 UTC, BillyTilly commented on config/config.go
> +	}
Да так будет лаконичнее

2024-02-20 09:05 UTC, BillyTilly commented on cmd/shortener/main.go
> +	r.GET("/:key", redirectHandler)
Добавил

2024-02-20 09:05 UTC, BillyTilly commented on cmd/shortener/main.go
> +	if stringedBody == "" {
Поправил

2024-02-21 22:56 UTC, valentinsoe commented on config/config.go
> +	if string(AppConfig.Host) != "localhost:8080" {
Я к сожалению не имею времени пролазить всю историю изменений, чтобы понять что именно не работало. Но точно этот тест падал по какой-то другой причине:)

2024-02-22 09:25 UTC, merged